# Generated by Django 2.1.4 on 2018-12-26 22:30

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstaCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(max_length=100)),
                ('catarray', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), size=40)),
            ],
            options={
                'verbose_name_plural': 'InstaCategories',
                'db_table': 'InstaCategories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InstaHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploads', models.IntegerField()),
                ('totalfollowers', models.IntegerField()),
                ('totalfollows', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('accountuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'InstaHistory',
                'db_table': 'InstaHistory',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LikeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('link', models.TextField()),
                ('date', models.DateTimeField()),
                ('accountuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'LikeHistory',
                'db_table': 'LikeHistory',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LikingPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likesperhour', models.IntegerField(default=60, validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(1)])),
                ('consecutivehours', models.IntegerField(default=7, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(1)])),
                ('likesperday', models.IntegerField(default=400, validators=[django.core.validators.MaxValueValidator(450), django.core.validators.MinValueValidator(1)])),
                ('minposts', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0)])),
                ('maxfollowers', models.IntegerField(default=400, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(1)])),
                ('minfollowers', models.IntegerField(default=400, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(1)])),
                ('enforceclarifai', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('enforcebanned', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('subscribedcategories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=15)),
                ('accountuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'LikingPreferences',
                'db_table': 'LikingPreferences',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instauser', models.CharField(max_length=100)),
                ('instapass', models.CharField(max_length=100)),
                ('clientid', models.CharField(max_length=100)),
                ('accesstoken', models.CharField(max_length=100)),
                ('startdate', models.DateTimeField()),
                ('accountuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'UserInfo',
                'db_table': 'UserInfo',
                'managed': True,
            },
        ),
    ]
