# Generated by Django 2.1.4 on 2018-12-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_auto_20181226_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='instapass',
            field=models.TextField(),
        ),
    ]
